### ISSUE TITLE
How to represent a shaft?

### ISSUE THREAD

**Issue by LeleuxJulie** [kaufmanno/gsdma_2021#3]

**Comment by MargotVanTrimpont** [comment]
the representation is the same that for the issue #4

**Comment by kaufmanno** [comment]
It would be worth looking at [geopandas ](https://geopandas.org/) and [shapely](https://shapely.readthedocs.io/en/stable/manual.html) for the GIS part and [pyvista](https://www.pyvista.org) for the 3d representation. I have some code to convert a geodataframe to an unstructured grid if your need it...

**Comment by MargotVanTrimpont** [comment]
maybe an idea to represent a tube in 3D with [pyvista](https://github.com/pyvista/pyvista/blob/main/pyvista/utilities/geometric_objects.py)

**Comment by kaufmanno** [comment]
@boblekiwi , @LeleuxJulie You could try this function to convert a geopandas geodataframe to a pyvista unstructured grid:

def gdf_to_ug(gdf, elevation='z'):
    """ Transforms a geopandas geodataframe into a pyvista unstructured grid

    Parameters
    ----------
    gdf : geopandas.GeoDataFrame
        A geodataframe with unique index values

    elevation : str
        Column name for the elevation field

    Returns
    -------
    pv.core.pointset.UnstructuredGrid
        A pyvista unstructured grid containing Point, LineString and Polygon with associated data
    """

    points = []
    point_cells = []
    tubes = {}
    cell_data = []
    k = 0
    point_idx = 0
    # iterate over the rows
    for idx, row in gdf.iterrows():
        if isinstance(row.geometry, Point):
            x, y, z = row.geometry.x, row.geometry.y, row[elevation]
            points.append([x, y, z])
            cell_data.append(row[elevation])
            point_cells.append([1, point_idx])
            point_idx += 1

        elif isinstance(row.geometry, LineString) or isinstance(row.geometry, Polygon):
            line_vertices = []

            # iterate over the vertices
            if isinstance(row.geometry, LineString):
                number_of_vertices = len(list(row.geometry.coords))
                vertices = zip(row.geometry.xy[0], row.geometry.xy[1], itertools.repeat(row[elevation]))
            elif isinstance(row.geometry, Polygon):
                number_of_vertices = len(list(row.geometry.exterior.coords))
                vertices = zip(row.geometry.exterior.xy[0], row.geometry.exterior.xy[1],
                               itertools.repeat(row[elevation]))
            else:
                print(f'Invalid geometry type : {type(row.geometry)}')
                return
            for vertex in vertices:
                line_vertices.append([vertex[0], vertex[1], vertex[2]])
            line_vertices = np.array(line_vertices)

            # get the number of vertices and create a cell sequence

            line_cells = np.array([number_of_vertices] + [i for i in range(number_of_vertices)])
            unstructured_grid = pv.UnstructuredGrid(line_cells, np.array([4]), line_vertices)
            # we can add some values to the point
            unstructured_grid.cell_arrays['Elevation'] = row[elevation]
            tubes[str(k)] = unstructured_grid
            k += 1

    if len(points) > 0:
        # Create an unstructured grid object for all the points and associate data
        unstructured_grid = pv.UnstructuredGrid(np.array(point_cells), np.array([1] * len(points)), np.array(points))
        unstructured_grid.cell_arrays['Elevation'] = cell_data

        # Merge tubes created from lines and
        tubes[str(k)] = unstructured_grid

    # print(tubes)
    blocks = pv.MultiBlock(tubes)
    unstructured_grid = blocks.combine()

    return unstructured_grid
